/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vishaluplanch.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AdapterEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2913676729789653406L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdapterEvent\",\"namespace\":\"com.vishaluplanch.avro.schema\",\"fields\":[{\"name\":\"eventId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"eventType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"publishedDate\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AdapterEvent> ENCODER =
      new BinaryMessageEncoder<AdapterEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AdapterEvent> DECODER =
      new BinaryMessageDecoder<AdapterEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AdapterEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AdapterEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AdapterEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AdapterEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AdapterEvent from a ByteBuffer. */
  public static AdapterEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence eventId;
  @Deprecated public java.lang.CharSequence eventType;
  @Deprecated public java.lang.CharSequence publishedDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AdapterEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param eventType The new value for eventType
   * @param publishedDate The new value for publishedDate
   */
  public AdapterEvent(java.lang.CharSequence eventId, java.lang.CharSequence eventType, java.lang.CharSequence publishedDate) {
    this.eventId = eventId;
    this.eventType = eventType;
    this.publishedDate = publishedDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return eventType;
    case 2: return publishedDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: eventType = (java.lang.CharSequence)value$; break;
    case 2: publishedDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.CharSequence getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'publishedDate' field.
   * @return The value of the 'publishedDate' field.
   */
  public java.lang.CharSequence getPublishedDate() {
    return publishedDate;
  }

  /**
   * Sets the value of the 'publishedDate' field.
   * @param value the value to set.
   */
  public void setPublishedDate(java.lang.CharSequence value) {
    this.publishedDate = value;
  }

  /**
   * Creates a new AdapterEvent RecordBuilder.
   * @return A new AdapterEvent RecordBuilder
   */
  public static com.vishaluplanch.avro.schema.AdapterEvent.Builder newBuilder() {
    return new com.vishaluplanch.avro.schema.AdapterEvent.Builder();
  }

  /**
   * Creates a new AdapterEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdapterEvent RecordBuilder
   */
  public static com.vishaluplanch.avro.schema.AdapterEvent.Builder newBuilder(com.vishaluplanch.avro.schema.AdapterEvent.Builder other) {
    return new com.vishaluplanch.avro.schema.AdapterEvent.Builder(other);
  }

  /**
   * Creates a new AdapterEvent RecordBuilder by copying an existing AdapterEvent instance.
   * @param other The existing instance to copy.
   * @return A new AdapterEvent RecordBuilder
   */
  public static com.vishaluplanch.avro.schema.AdapterEvent.Builder newBuilder(com.vishaluplanch.avro.schema.AdapterEvent other) {
    return new com.vishaluplanch.avro.schema.AdapterEvent.Builder(other);
  }

  /**
   * RecordBuilder for AdapterEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdapterEvent>
    implements org.apache.avro.data.RecordBuilder<AdapterEvent> {

    private java.lang.CharSequence eventId;
    private java.lang.CharSequence eventType;
    private java.lang.CharSequence publishedDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vishaluplanch.avro.schema.AdapterEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publishedDate)) {
        this.publishedDate = data().deepCopy(fields()[2].schema(), other.publishedDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AdapterEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vishaluplanch.avro.schema.AdapterEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publishedDate)) {
        this.publishedDate = data().deepCopy(fields()[2].schema(), other.publishedDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.vishaluplanch.avro.schema.AdapterEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.vishaluplanch.avro.schema.AdapterEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.vishaluplanch.avro.schema.AdapterEvent.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.eventType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.vishaluplanch.avro.schema.AdapterEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublishedDate() {
      return publishedDate;
    }

    /**
      * Sets the value of the 'publishedDate' field.
      * @param value The value of 'publishedDate'.
      * @return This builder.
      */
    public com.vishaluplanch.avro.schema.AdapterEvent.Builder setPublishedDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.publishedDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedDate' field has been set.
      * @return True if the 'publishedDate' field has been set, false otherwise.
      */
    public boolean hasPublishedDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'publishedDate' field.
      * @return This builder.
      */
    public com.vishaluplanch.avro.schema.AdapterEvent.Builder clearPublishedDate() {
      publishedDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AdapterEvent build() {
      try {
        AdapterEvent record = new AdapterEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.eventType = fieldSetFlags()[1] ? this.eventType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.publishedDate = fieldSetFlags()[2] ? this.publishedDate : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AdapterEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AdapterEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AdapterEvent>
    READER$ = (org.apache.avro.io.DatumReader<AdapterEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
